import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { SURAHS } from "../../../data/surahs";
import { ALL_TRANSLATIONS } from "../../../lib/constants";
import { getTranslation } from "../../../lib/translationLoader";
import { apiRateGuard } from "../../../lib/apiRateLimit";
import quranText from "../../../data/quran-text.json";

const EDITIONS = ALL_TRANSLATIONS;

const CACHE_HEADERS = {
  "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=604800"
};

type ArabicVerse = {
  number: number;
  text: string;
  tajweed: string | null;
  page: number | null;
};

// Local Arabic text comes from app/data/quran-text.json, which is regenerated by
// scripts/fetch-quran-data.mjs from Quran.com's word-level text_uthmani build.
// That build is character-identical to /api/words, so the playing-state and
// idle-state Arabic always match (no annotation pop-in). Re-run the script when
// you want to refresh.
type LocalQuranEntry = {
  ar?: string;
  en?: string;
  tj?: string | null;
  pg?: number | null;
};
type LocalQuranData = Record<string, Record<string, LocalQuranEntry>>;
const QURAN_TEXT = quranText as unknown as LocalQuranData;

const getLocalArabicVerses = (surahNumber: number): ArabicVerse[] => {
  const surahData = QURAN_TEXT[String(surahNumber)];
  if (!surahData) return [];
  const verses: ArabicVerse[] = [];
  for (const [ayahKey, entry] of Object.entries(surahData)) {
    const number = Number(ayahKey);
    if (!Number.isFinite(number)) continue;
    verses.push({
      number,
      text: entry.ar || "",
      tajweed: entry.tj ?? null,
      page: entry.pg ?? null,
    });
  }
  verses.sort((a, b) => a.number - b.number);
  return verses;
};

type RouteContext = {
  params: { id: string } | Promise<{ id: string }>;
};

export async function GET(request: NextRequest, { params }: RouteContext) {
  const blocked = await apiRateGuard(request, "api-surah");
  if (blocked) return blocked;

  const { id } = await Promise.resolve(params);
  const surahNumber = Number(id);

  if (!id || !Number.isInteger(surahNumber) || surahNumber < 1 || surahNumber > 114) {
    return NextResponse.json({ error: "Invalid surah id." }, { status: 400 });
  }

  try {
    const transliterationParam = String(
      request.nextUrl.searchParams.get("transliteration") || ""
    ).toLowerCase();
    const includeTransliteration = ["1", "true", "yes", "on"].includes(
      transliterationParam
    );

    const allowedTranslationIds = new Set(EDITIONS.map((e) => e.id));
    const translationsParam = request.nextUrl.searchParams.get("translations") || "";
    const requestedIds = translationsParam
      .split(",")
      .map((value) => value.trim())
      .filter(Boolean)
      .filter((value) => allowedTranslationIds.has(value));

    const translationIds: string[] = [];
    const seen = new Set<string>();
    for (const translationId of (requestedIds.length ? requestedIds : ["en-arberry"])) {
      if (seen.has(translationId)) continue;
      if (!allowedTranslationIds.has(translationId)) continue;
      seen.add(translationId);
      translationIds.push(translationId);
    }

    // 1. Get surah metadata from local data
    const surahMeta = SURAHS.find((s) => s.number === surahNumber);
    if (!surahMeta) {
      return NextResponse.json({ error: "Surah not found." }, { status: 404 });
    }

    // 2. Load only requested translations from local files (in parallel)
    const translationResults = await Promise.all(
      translationIds.map(async (translationId) => ({
        id: translationId,
        verses: await getTranslation(translationId, surahNumber)
      }))
    );
    const transliterationByAyah = includeTransliteration
      ? await getTranslation("en-transliteration", surahNumber)
      : null;

    // 3. Read Arabic + tajweed + page from local quran-text.json (regenerated
    //    by scripts/fetch-quran-data.mjs from Quran.com's word-level build).
    const arabicVerses = getLocalArabicVerses(surahNumber);
    const arabicByNumber = new Map<number, ArabicVerse>(
      arabicVerses.map((verse) => [verse.number, verse])
    );

    // 4. Merge Data
    const ayahs: Array<{
      number: number;
      arabic: string;
      arabicTajweed: string | null;
      transliteration?: string;
      pageNumber: number | null;
      translations: Record<string, { text: string }>;
    }> = [];

    const totalAyahs = surahMeta.ayahCount;

    for (let i = 1; i <= totalAyahs; i++) {
      const arabicEntry = arabicByNumber.get(i);
      const arabicText = arabicEntry?.text || "Arabic text unavailable";
      const arabicTajweed = arabicEntry?.tajweed || null;
      const pageNumber = arabicEntry?.page || null;

      const translations: Record<string, { text: string }> = {};
      for (const result of translationResults) {
        const text = result.verses?.get(i);
        if (text) {
          translations[result.id] = { text };
        }
      }

      ayahs.push({
        number: i,
        arabic: arabicText,
        arabicTajweed,
        transliteration: transliterationByAyah?.get(i) || undefined,
        pageNumber,
        translations
      });
    }

    return NextResponse.json(
      {
        surah: {
          number: surahMeta.number,
          name: surahMeta.arabicName,
          englishName: surahMeta.englishName,
          englishNameTranslation: surahMeta.translation,
          numberOfAyahs: surahMeta.ayahCount,
          revelationType: surahMeta.revelationType
        },
        ayahs,
        arabicScript: "uthmani",
        translationOrder: translationIds
      },
      { headers: CACHE_HEADERS }
    );
  } catch (error) {
    console.error("API Error:", error);
    return NextResponse.json(
      { error: "Unable to load Surah data." },
      { status: 502 }
    );
  }
}
